language: ruby
cache:
  - bundler
  - npm
bundler_args: --path ../../vendor/bundle --without debug
node_js:
  - "6"
  - "7.0"
  - "8.0"
  - "stable"
gemfile:
  - test/gemfiles/rails_head.gemfile
  - test/gemfiles/sass_3_3.gemfile
  - test/gemfiles/sass_3_4.gemfile
  - test/gemfiles/sass_head.gemfile
before_script:
  - npm install -g node-sass
  - npm install
matrix:
    allow_failures:
    - gemfile: test/gemfiles/rails_head.gemfile
    - gemfile: test/gemfiles/sass_head.gemfile
env:
    global:
    - VERBOSE=1
script:
  - sh test/node_sass_compile_test.sh
