language: node_js
cache:
  directories:
    - node_modules
node_js:
    - "8.10.0"
    - "stable"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn add global node-sass
  - yarn install
script:
  - npm run test
